// Generated by CoffeeScript 1.7.1
Crafty.c('Map', {
  map: function(game) {
    var tile_position, _i, _len, _ref, _results;
    this.requires('Tile');
    _ref = game.map_grid.positions;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      tile_position = _ref[_i];
      _results.push(Crafty.e('Tile').tile(tile_position).dbg());
    }
    return _results;
  }
});

Crafty.c('Tile', {
  soldiers: 0,
  type: 0,
  value: 50,
  owner: 0,
  tile: function(tile_position) {
    this.requires('2D, DOM, Image');
    this.width = 128;
    this.height = this.width;
    this.size = this.width / 2;
    this.attr({
      q: tile_position.q,
      r: tile_position.r,
      x: this.size * 3 / 2 * tile_position.q,
      y: this.size * Math.sqrt(3) * (tile_position.r + tile_position.q / 2)
    });
    this.owner = tile_position.owner;
    this.units = tile_position.units;
    return this.image('assets/cell_player' + (this.owner != null ? this.owner.id : '0') + '.png');
  },
  dbg: function() {
    var dbgMsg;
    return dbgMsg = Crafty.e('2D, DOM, Text').attr({
      x: this.x + 40,
      y: this.y + 40,
      w: 128
    }).text(this.q + " / " + this.r + "<br/>Einheiten: " + (this.units != null ? this.units.length : '0'));
  }
});
