// Generated by CoffeeScript 1.7.1
Crafty.scene('Level', function(game) {
  Crafty.viewport.mouselook(true);
  return Crafty.e('Map').map(game);
});

Crafty.scene('Menu', function(game) {
  return Crafty.e('2D, DOM, Text').attr({
    x: 0,
    y: game.height / 2 - 24,
    w: game.width
  }).text("Loading ...").textFont({
    'weight': 'bold',
    'size': '50px'
  }).css({
    'text-align': 'center',
    'color': '#333'
  });
});
