// Generated by CoffeeScript 1.7.1
Crafty.scene('Level', function(game) {
  var center, map;
  Crafty.viewport.mouselook(true);
  map = Crafty.e('Map').map(game);
  center = map.getCenter();
  Crafty.viewport.x = -center.x + window.innerWidth / 2;
  return Crafty.viewport.y = -center.y + window.innerHeight / 2;
});

Crafty.scene('Menu', function(game) {
  return Crafty.e('2D, DOM, Text').attr({
    x: 0,
    y: game.height / 2 - 24,
    w: game.width
  }).text("Loading ...").textFont({
    'weight': 'bold',
    'size': '50px'
  }).css({
    'text-align': 'center',
    'color': '#333'
  });
});
