// Generated by CoffeeScript 1.7.1
var Game, MapGrid, Tile;

Tile = (function() {
  function Tile(width) {
    this.width = width;
    this.width = width;
    this.height = width;
    this.size = width / 2;
  }

  return Tile;

})();

MapGrid = (function() {
  function MapGrid(tile_width, radius) {
    this.radius_q = radius;
    this.radius_r = radius;
    this.tile = new Tile(tile_width);
    this.width = (this.radius_q * 2 + 1) * this.tile.width;
    this.height = (this.radius_r * 2 + 1) * this.tile.width;
  }

  return MapGrid;

})();

Game = (function() {
  function Game(tile_width, radius, min_dense, threshold) {
    this.map_grid = new MapGrid(tile_width, radius);
    this.width = this.map_grid.width;
    this.height = this.map_grid.height;
    this.map_generator = new MapGenerator(this.map_grid.radius_q, this.map_grid.radius_r, min_dense, threshold);
  }

  Game.prototype.start = function() {
    Crafty.init(this.width, this.height);
    Crafty.background('rgb(249, 223, 125)');
    Crafty.load(['assets/cell_default.png'], function() {});
    return Crafty.scene('Menu', this);
  };

  return Game;

})();

window.onload = function() {
  var game;
  game = new Game(128, 3, 0.2, 0.3);
  return game.start();
};
