// Generated by CoffeeScript 1.7.1
var Game, MapGrid, Settings, Tile;

Tile = (function() {
  function Tile(width) {
    this.width = width;
    this.width = width;
    this.height = width;
    this.size = width / 2;
  }

  return Tile;

})();

MapGrid = (function() {
  function MapGrid(tile_width, radius) {
    this.radius_q = radius;
    this.radius_r = radius;
    this.tile = new Tile(tile_width);
    this.width = (this.radius_q * 2 + 1) * this.tile.width;
    this.height = (this.radius_r * 2 + 1) * this.tile.width;
  }

  return MapGrid;

})();

Game = (function() {
  function Game(tile_width, radius, min_dense, threshold) {
    this.map_grid = new MapGrid(tile_width, radius);
    this.width = this.map_grid.width;
    this.height = this.map_grid.height;
    this.map_generator = new MapGenerator(this.map_grid.radius_q, this.map_grid.radius_r, min_dense, threshold);
  }

  Game.prototype.start = function() {
    Crafty.init(window.width, window.height);
    Crafty.background('rgb(249, 223, 125)');
    return Crafty.load(['assets/cell_player0.png', 'assets/cell_player1.png', 'assets/cell_player2.png'], (function(_this) {
      return function() {
        return Crafty.scene('Level', _this);
      };
    })(this));
  };

  return Game;

})();

Settings = (function() {
  function Settings() {}

  Settings.tileWidthPx = 128;

  Settings.tileBoundary = 3;

  Settings.minTileDense = 0.2;

  Settings.mapGenRandom = 0.3;

  return Settings;

})();

window.onload = function() {
  var game;
  game = new Game(Settings.tileWidthPx, Settings.tileBoundary, Settings.minTileDense, Settings.mapGenRandom);
  return game.start();
};
