// Generated by CoffeeScript 1.7.1
Crafty.c('Grid', {
  pos: function(q, r, size) {
    this.attr({
      q: q,
      r: r,
      x: size * 3 / 2 * q,
      y: size * Math.sqrt(3) * (r + q / 2)
    });
    return this;
  }
});
