// Generated by CoffeeScript 1.7.1
Crafty.c('Map', {
  map: function(game) {
    var tile_position, tile_positions, _i, _len, _results;
    this.requires('Cell');
    tile_positions = game.map_generator.generate();
    _results = [];
    for (_i = 0, _len = tile_positions.length; _i < _len; _i++) {
      tile_position = tile_positions[_i];
      _results.push(Crafty.e('Cell').cell(tile_position.q, tile_position.r).pos(tile_position.q, tile_position.r, game.map_grid.tile.size));
    }
    return _results;
  }
});

Crafty.c('Cell', {
  cell: function(q, r) {
    var dbgMsg;
    this.requires('2D, DOM, Grid, Image').image('assets/cell_default.png');
    dbgMsg = Crafty.e('2D, DOM, Text').attr({
      x: 40,
      y: 40,
      w: 128
    }).text(q + " / " + r);
    return this.attach(dbgMsg);
  }
});
