// Generated by CoffeeScript 1.7.1
Crafty.c('Map', {
  map: function(game) {
    var q, r, _i, _ref, _ref1, _results;
    this.requires('Cell');
    _results = [];
    for (q = _i = _ref = -game.map_grid.radius_q, _ref1 = game.map_grid.radius_q + 1; _ref <= _ref1 ? _i < _ref1 : _i > _ref1; q = _ref <= _ref1 ? ++_i : --_i) {
      _results.push((function() {
        var _j, _ref2, _ref3, _results1;
        _results1 = [];
        for (r = _j = _ref2 = -game.map_grid.radius_r, _ref3 = game.map_grid.radius_r + 1; _ref2 <= _ref3 ? _j < _ref3 : _j > _ref3; r = _ref2 <= _ref3 ? ++_j : --_j) {
          if (q + r <= game.map_grid.radius_q && q + r >= -game.map_grid.radius_q) {
            _results1.push(Crafty.e('Cell').cell(q, r).pos(q, r, game.map_grid.tile.size));
          } else {
            _results1.push(void 0);
          }
        }
        return _results1;
      })());
    }
    return _results;
  }
});

Crafty.c('Cell', {
  cell: function(q, r) {
    var dbgMsg;
    this.requires('2D, DOM, Grid, Image').image('assets/cell_default.png');
    dbgMsg = Crafty.e('2D, DOM, Text').attr({
      x: 40,
      y: 40,
      w: 128
    }).text(q + " / " + r);
    return this.attach(dbgMsg);
  }
});
